sudo: require
services:
  - docker

before_install:
  - docker build -t brad/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true brad/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "React-env"
  bucket_name: "elasticbeanstalk-us-east-1-317358458417"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
